/**
 * Affiliate dashboard API endpoints.
 * Covers the user-facing affiliate stats panel and the admin aggregate/detail dashboard views.
 * CRUD admin operations (code overrides, rate changes, bulk actions) live in api/admin/affiliate.ts.
 */

import { apiClient } from './client'

// ==================== Shared sub-types ====================

/** One calendar day's aggregated affiliate activity. */
export interface DailyRollupRow {
  /** Calendar date, YYYY-MM-DD */
  date: string
  /** New invitees who registered that day */
  new_invitees: number
  /** Total recharge amount credited to invitees that day (quota units) */
  recharge_amount: number
  /** Rebate earned by the affiliate that day */
  rebate_amount: number
}

/** Aggregated stats for a named time period, with a daily breakdown. */
export interface AffiliatePeriodStats {
  /** Period identifier passed in the request, e.g. 'today' | 'week' | 'month' | 'year' */
  period: string
  /** Inclusive start of the resolved date range, YYYY-MM-DD */
  start_date: string
  /** Inclusive end of the resolved date range, YYYY-MM-DD */
  end_date: string
  /** New invitees registered within the period */
  new_invitees: number
  /** Total recharge by all invitees within the period */
  total_recharge: number
  /** Total rebate earned within the period */
  total_rebate: number
  /** Rebate that has been credited but not yet withdrawn */
  pending_rebate: number
  /** Per-day breakdown (empty when period is 'today') */
  daily: DailyRollupRow[]
}

/** A single entry in the affiliate leaderboard. */
export interface AffiliateRankEntry {
  rank: number
  user_id: number
  username: string
  /** Affiliate referral code */
  aff_code: string
  /** New invitees brought in during the period */
  new_invitees: number
  /** Total recharge generated by this affiliate's invitees */
  recharge_amount: number
  /** Total rebate earned by this affiliate */
  rebate_amount: number
}

// ==================== User-facing types ====================

/** Full affiliate dashboard payload returned for the currently authenticated user. */
export interface UserAffiliateDashboard {
  /** Referral code assigned to the user */
  aff_code: string
  /** Whether the code was set by the user (custom) or auto-generated */
  aff_code_custom: boolean
  /** Total number of users invited across all time */
  aff_count: number
  /** Current available rebate balance (quota units) */
  aff_quota: number
  /** All-time rebate earned (quota units) */
  aff_history_quota: number
  /** All-time rebate transferred/withdrawn */
  transferred_rebate_total: number
  /** Period-scoped stats including the daily breakdown */
  stats: AffiliatePeriodStats
}

// ==================== Admin dashboard types ====================

/** Admin aggregate view — platform-wide affiliate activity for a period. */
export interface AdminAffiliateOverview {
  /** Period identifier used in the request */
  period: string
  /** Inclusive start of the resolved date range, YYYY-MM-DD */
  start_date: string
  /** Inclusive end of the resolved date range, YYYY-MM-DD */
  end_date: string
  /** Count of affiliates who had any activity in the period */
  active_affiliates: number
  /** Total new invitees across all affiliates in the period */
  total_new_invitees: number
  /** Total recharge generated by all invitees in the period */
  total_recharge: number
  /** Total rebate issued to all affiliates in the period */
  total_rebate_issued: number
  /** Top affiliates by rebate for the period */
  top_affiliates: AffiliateRankEntry[]
  /** Platform-wide daily rollup for the period */
  daily: DailyRollupRow[]
}

/** Admin detail view for a single affiliate user, including their period stats. */
export interface AffiliateDetail {
  user_id: number
  email: string
  username: string
  aff_code: string
  /** Custom rebate rate override in percent; null means the platform default applies */
  aff_rebate_rate_percent: number | null
  /** Total lifetime invitees */
  aff_count: number
  /** Current available rebate balance */
  aff_quota: number
  /** Rebate frozen pending confirmation */
  aff_frozen_quota: number
  /** All-time earned rebate */
  aff_history_quota: number
  /** All-time withdrawn rebate */
  transferred_rebate_total: number
  /** All-time total recharge by this affiliate's invitees */
  invitee_recharge_total: number
  /** Period-scoped stats for this user */
  stats: AffiliatePeriodStats
}

// ==================== API functions ====================

/**
 * Fetch affiliate dashboard stats for the currently authenticated user.
 * @param period - Time period: 'today' | 'week' | 'month' | 'year' (default: 'month')
 * @returns Full affiliate dashboard including balance summary and period stats
 */
export async function fetchAffiliateStats(period: string = 'month'): Promise<UserAffiliateDashboard> {
  const { data } = await apiClient.get<UserAffiliateDashboard>('/affiliate/stats', {
    params: { period }
  })
  return data
}

/**
 * Fetch platform-wide affiliate activity overview (admin only).
 * @param period - Time period: 'today' | 'week' | 'month' | 'year' (default: 'month')
 * @returns Aggregate overview with top-affiliate leaderboard and daily rollup
 */
export async function fetchAdminAffiliateOverview(
  period: string = 'month'
): Promise<AdminAffiliateOverview> {
  const { data } = await apiClient.get<AdminAffiliateOverview>('/admin/affiliates/overview', {
    params: { period }
  })
  return data
}

/**
 * Fetch detailed affiliate stats for a single user (admin only).
 * @param id - Target user's ID
 * @param period - Time period: 'today' | 'week' | 'month' | 'year' (default: 'month')
 * @returns Full affiliate profile including balance fields and period stats
 */
export async function fetchAdminAffiliateDetail(
  id: number,
  period: string = 'month'
): Promise<AffiliateDetail> {
  const { data } = await apiClient.get<AffiliateDetail>(`/admin/affiliates/users/${id}/stats`, {
    params: { period }
  })
  return data
}

// ==================== Namespace export ====================

export const affiliateDashboardAPI = {
  fetchAffiliateStats,
  fetchAdminAffiliateOverview,
  fetchAdminAffiliateDetail
}

export default affiliateDashboardAPI
