//go:build unit

package service

import (
	"context"
	"encoding/base64"
	"testing"

	"github.com/stretchr/testify/require"
)

type userAvatarRepoStub struct {
	userRepoStub
	avatar    *UserAvatar
	avatarUID int64
}

func (s *userAvatarRepoStub) GetUserAvatar(_ context.Context, userID int64) (*UserAvatar, error) {
	s.avatarUID = userID
	return s.avatar, nil
}

func (s *userAvatarRepoStub) UpsertUserAvatar(_ context.Context, userID int64, input UpsertUserAvatarInput) (*UserAvatar, error) {
	s.avatarUID = userID
	s.avatar = &UserAvatar{
		StorageProvider: input.StorageProvider,
		StorageKey:      input.StorageKey,
		URL:             input.URL,
		ContentType:     input.ContentType,
		ByteSize:        input.ByteSize,
		SHA256:          input.SHA256,
	}
	return s.avatar, nil
}

func (s *userAvatarRepoStub) DeleteUserAvatar(_ context.Context, userID int64) error {
	s.avatarUID = userID
	s.avatar = nil
	return nil
}

func TestValidateUserAvatarUploadRequiresSupportedRealImage(t *testing.T) {
	// A 1x1 PNG generated by the browser canvas path.
	png := "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="

	require.NoError(t, ValidateUserAvatarUpload("data:image/png;base64,"+png))
	require.ErrorIs(t, ValidateUserAvatarUpload("data:image/gif;base64,"+png), ErrAvatarNotImage)
	require.ErrorIs(t, ValidateUserAvatarUpload("data:image/png;base64,"+base64.StdEncoding.EncodeToString([]byte("not an image"))), ErrAvatarNotImage)
	require.ErrorIs(t, ValidateUserAvatarUpload("https://example.com/avatar.png"), ErrAvatarInvalid)
}

func TestUserServiceAvatarUsesAuthenticatedRepositoryIdentity(t *testing.T) {
	repo := &userAvatarRepoStub{}
	svc := NewUserService(repo, nil, nil)
	const userID int64 = 42

	png := "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
	avatar, err := svc.SetAvatar(context.Background(), userID, "data:image/png;base64,"+png)
	require.NoError(t, err)
	require.Equal(t, userID, repo.avatarUID)
	require.Equal(t, "image/png", avatar.ContentType)

	loaded, err := svc.GetAvatar(context.Background(), userID)
	require.NoError(t, err)
	require.Equal(t, userID, repo.avatarUID)
	require.Equal(t, avatar.URL, loaded.URL)

	_, err = svc.SetAvatar(context.Background(), userID, "")
	require.NoError(t, err)
	require.Nil(t, repo.avatar)
}
