bind 127.0.0.1
protected-mode yes
port 6380
tcp-backlog 511
timeout 0
tcp-keepalive 300

daemonize no
supervised systemd
pidfile /run/redis-staging/redis-server.pid

loglevel notice
logfile ""

databases 16
save ""
stop-writes-on-bgsave-error no
dbfilename dump.rdb
dir /var/lib/redis-staging
appendonly no

maxmemory 256mb
maxmemory-policy allkeys-lru
